# Generated by Django 2.0.9 on 2018-11-04 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagmisperris', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
